package org.phoenixframework.liveview.domain.base

object ComposableTypes {
    const val alertDialog = "AlertDialog"
    const val asyncImage = "AsyncImage"
    const val badgedBox = "BadgedBox"
    const val box = "Box"
    const val button = "Button"
    const val card = "Card"
    const val checkbox = "CheckBox"
    const val circularProgressIndicator = "CircularProgressIndicator"
    const val column = "Column"
    const val divider = "Divider"
    const val dropdownMenuItem = "DropdownMenuItem"
    const val elevatedButton = "ElevatedButton"
    const val elevatedCard = "ElevatedCard"
    const val exposedDropdownMenuBox = "ExposedDropdownMenuBox"
    const val extendedFab = "ExtendedFloatingActionButton"
    const val fab = "FloatingActionButton"
    const val filledTonalButton = "FilledTonalButton"
    const val icon = "Icon"
    const val iconButton = "IconButton"
    const val image = "Image"
    const val largeFab = "LargeFloatingActionButton"
    const val lazyColumn = "LazyColumn"
    const val lazyRow = "LazyRow"
    const val lazyVerticalGrid = "LazyVerticalGrid"
    const val linearProgressIndicator = "LinearProgressIndicator"
    const val modalBottomSheet = "ModalBottomSheet"
    const val modalDrawerSheet = "ModalDrawerSheet"
    const val modalNavigationDrawer = "ModalNavigationDrawer"
    const val navigationDrawerItem = "NavigationDrawerItem"
    const val outlinedButton = "OutlinedButton"
    const val outlinedCard = "OutlinedCard"
    const val outlinedTextField = "OutlinedTextField"
    const val radioButton = "RadioButton"
    const val rangeSlider = "RangeSlider"
    const val row = "Row"
    const val scaffold = "Scaffold"
    const val slider = "Slider"
    const val smallFab = "SmallFloatingActionButton"
    const val spacer = "Spacer"
    const val switch = "Switch"
    const val text = "Text"
    const val textButton = "TextButton"
    const val textField = "TextField"
    const val topAppBar = "TopAppBar"
}