package org.phoenixframework.liveview.domain.base

object ComposableTypes{
    const val spacer: String = "spacer"
    const val topBar= "topbar"
    const val scaffold = "scaffold"
    const val column = "column"
    const val row = "row"
    const val lazyColumn = "lazy-column"
    const val lazyRow = "lazy-row"
    const val text = "text"
    const val card = "card"
    const val asyncImage = "async-image"
    const val navHost = "nav-host"
    const val navGraph = "nav-graph"
    const val navDestination = "nav-destination"
    const val textField = "text-field"
    const val button = "button"
    const val iconButton = "icon-button"
    const val icon = "icon"
    const val checkBox = "checkbox"
    const val radioGroup = "radio-group"
    const val radio = "radio"
    const val switch = "switch"
    const val slider = "slider"
    const val progressIndicator = "progress-indicator"
    const val circularProgressIndicator = "circular-progress-indicator"
    const val linearProgressIndicator = "linear-progress-indicator"
    const val snackbar = "snackbar"
    const val alertDialog = "alert-dialog"
    const val dialog = "dialog"
    const val bottomSheetScaffold = "bottom-sheet-scaffold"
    const val bottomSheet = "bottom-sheet"
    const val bottomNavigation = "bottom-navigation"
    const val bottomNavigationItem = "bottom-navigation-item"
    const val tabRow = "tab-row"
    const val tab = "tab"
    const val item = "item"

}