package org.phoenixframework.liveview.constants

object ModifierTypes {
    const val typeAlignment = "Alignment"
    const val typeBorderStroke = "BorderStroke"
    const val typeBrush = "Brush"
    const val typeColor = "Color"
    const val typeDp = "Dp"
    const val typeDpSize = "DpSize"
    const val typeEvent = "__event__"
    const val typeIntrinsicSize = "IntrinsicSize"
    const val typeIntOffset = "IntOffset"
    const val typeIntSize = "IntSize"
    const val typeOffset = "Offset"
    const val typeRange = ".."
    const val typeRole = "Role"
    const val typeShape = "Shape"
    const val typeStartOffset = "StartOffset"
    const val typeTextUnit = "TextUnit"
    const val typeTextUnitType = "TextUnitType"
    const val typeTextUnitEm = "Em"
    const val typeTextUnitSp = "Sp"
    const val typeToggleableState = "ToggleableState"
    const val typeTransformOrigin = "TransformOrigin"
    const val typeUnitDp = "dp"
    const val typeUnitEm = "em"
    const val typeUnitSp = "sp"
    const val typeWindowInsets = "WindowInsets"
}