package org.phoenixframework.liveview.constants

object Templates {
    const val templateAction = "action"
    const val templateAvatar = "avatar"
    const val templateBackgroundContent = "backgroundContent"
    const val templateBadge = "badge"
    const val templateBody = "body"
    const val templateBottomBar = "bottomBar"
    const val templateConfirmButton = "confirm"
    const val templateContent = "content"
    const val templateDismissButton = "dismiss"
    const val templateDivider = "divider"
    const val templateDragHandle = "dragHandle"
    const val templateDrawerContent = "drawerContent"
    const val templateEndThumb = "endThumb"
    const val templateError = "error"
    const val templateFab = "fab"
    const val templateHeader = "header"
    const val templateHeadline = "headline"
    const val templateHeadlineContent = "headlineContent"
    const val templateIcon = "icon"
    const val templateLabel = "label"
    const val templateLeadingContent = "leadingContent"
    const val templateLeadingIcon = "leadingIcon"
    const val templateLoading = "loading"
    const val templateNavigationIcon = "navigationIcon"
    const val templateOverlineContent = "overlineContent"
    const val templatePlaceholder = "placeholder"
    const val templatePrefix = "prefix"
    const val templateSheetContent = "sheetContent"
    const val templateStartThumb = "startThumb"
    const val templateSuffix = "suffix"
    const val templateSupportingContent = "supportingContent"
    const val templateSupportingText = "supportingText"
    const val templateText = "text"
    const val templateThumb = "thumb"
    const val templateTitle = "title"
    const val templateTooltip = "tooltip"
    const val templateTrack = "track"
    const val templateTrailingContent = "trailingContent"
    const val templateTrailingIcon = "trailingIcon"
    const val templateTopBar = "topBar"
}